# Generated by Django 3.2.12 on 2022-03-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'Heroes'},
        ),
        migrations.CreateModel(
            name='HeroAcquaintance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.hero')),
            ],
        ),
    ]
