# Generated by Django 3.2.12 on 2022-03-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20220328_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroacquaintance',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='entities.category'),
            preserve_default=False,
        ),
    ]
