# Generated by Django 3.2.12 on 2022-03-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhero',
            options={'verbose_name_plural': 'Event heroes'},
        ),
    ]
